development:
  adapter: mysql2
  encoding: utf8
  database: tt_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: tt_test
  pool: 5
  username: root
  password:
