development:
  adapter: mysql2
  encoding: utf8
  database: helloworld_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: helloworld_test
  pool: 5
  username: root
  password:
